from enum import Enum

class WithQPutRequestBody_type(str, Enum):
    Short_text = "short_text",
    Long_text = "long_text",
    Mcq = "mcq",
    Multi_select = "multi_select",
    Rating = "rating",
    Date = "date",
    Number = "number",
    Yes_no = "yes_no",
    File_upload = "file_upload",
    Dropdown = "dropdown",
    Digital_signature = "digital_signature",
    Email = "email",
    Phone = "phone",
    Initials = "initials",
    Url = "url",
    Time = "time",
    Date_range = "date_range",
    Address = "address",
    Slider = "slider",
    Currency = "currency",
    Heading = "heading",
    Divider = "divider",
    Picture_choice = "picture_choice",
    Checkbox = "checkbox",
    Ranking = "ranking",
    Matrix = "matrix",
    Opinion_scale = "opinion_scale",
    Calculation = "calculation",
    Payment = "payment",

