from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from ......models.file_download_response import FileDownloadResponse
    from .file_download_response401_error import FileDownloadResponse401Error
    from .file_download_response403_error import FileDownloadResponse403Error
    from .file_download_response404_error import FileDownloadResponse404Error

class DownloadRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/files/{fileId}/download
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new DownloadRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/files/{fileId}/download", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[FileDownloadResponse]:
        """
        Returns a short-lived signed URL for a response upload or signed PDF file. Requires the submissions:download_files permission.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[FileDownloadResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from .file_download_response401_error import FileDownloadResponse401Error
        from .file_download_response403_error import FileDownloadResponse403Error
        from .file_download_response404_error import FileDownloadResponse404Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "401": FileDownloadResponse401Error,
            "403": FileDownloadResponse403Error,
            "404": FileDownloadResponse404Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from ......models.file_download_response import FileDownloadResponse

        return await self.request_adapter.send_async(request_info, FileDownloadResponse, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Returns a short-lived signed URL for a response upload or signed PDF file. Requires the submissions:download_files permission.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> DownloadRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: DownloadRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return DownloadRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class DownloadRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

